config/routes.rb
Rails.application.routes.draw do

  resources :wz_cases do
    collection do
      get 'begin'
      get 'confirm'
      get 'delete_all'
    end
  end
  root 'wz_cases#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_one :wz_case
end

app/models/wz_case.rb
class WzCase < ApplicationRecord
  belongs_to :vehicle
  has_one :wz_item, :dependent=> :delete
  has_one :wz_query,:dependent=> :delete

  def get_wz_items
    WzCase.parse wz_item
  end

  def get_wz_queries
    WzCase.parse wz_query
  end

  class << self
    def parse i
      return [] unless i
      str_ = i.info
      return [] unless str_
      items = eval str_
      return [] unless items && items.size > 0
      items
    end

    def get_des status_
      return "一致" if status_ == 0
      return "结果包含基准" if status_ == 1
      return "不同" if status_ == 2
      return "未知"
    end
  end
end

app/models/wz_item.rb
class WzItem < ApplicationRecord
end

app/models/wz_query.rb
class WzQuery < ApplicationRecord
  belongs_to :wz_case
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/wz_cases_controller.rb
require 'FileHelper'
require 'query_helper'
require 'json'
class WzCasesController < ApplicationController
  def index
    per_page = 28
    items = nil
    t = params[:type]
    if t
      items = WzCase.where(status: t.to_i)
    else
      items = WzCase.all
    end
    @wz_cases = items.order(id: :asc).page(params[:page]).per_page(per_page)
  end

  def create
    file_input = params[:fileMain]
    if file_input
      lst_vehicle = ::FileHelper.try_save_and_parse_data(file_input, "vehicle", request.remote_ip(), 4)
      if lst_vehicle
        lst_vehicle.each do |v_|
          plate_ = v_[1]
          vehicles = Vehicle.where(plate: plate_)
          found_same = vehicles.select{|i_| !i_.wz_case.nil?}
          next if found_same.size > 0
          new_v = Vehicle.create({cityname: v_[0], plate: plate_, frame: v_[3], engine: v_[2]})
          new_c = WzCase.create
          new_c.vehicle = new_v
          new_c.save
        end
        redirect_to wz_cases_path, notice: "上传成功!"
        return
      end
    end
    redirect_to wz_cases_path, notice: "上传失败!"
  end

  def show
    @item = WzCase.find(params[:id])
  end

  def edit
  end

  def update
    set_confirm WzCase.find(params[:id])
    redirect_to wz_cases_path, notice: "ok!"
  end

  def destroy
    @item = WzCase.find(params[:id])
    @item.delete
    redirect_to wz_cases_path, notice: "删除成功!"
  end

  def begin
    same =0
    contain = 1
    diff = 2
    res_hash = QueryHelper.loop WzCase.all
    WzCase.all.each do |wzcase|
      res_ = res_hash.fetch(wzcase.id, nil)
      unless res_
        wzcase.status = diff
        wzcase.wz_query = nil
        wzcase.save
        next
      end
      base = wzcase.get_wz_items
      if base == res_
        wzcase.status = same
        wzcase.save
        next
      end
      wzcase.create_wz_query(info: res_.to_json)
      unless base.index { |e_| !res_.index { |sub_e| sub_e == e_ } }
        wzcase.status = contain
        wzcase.save
        next
      end
      wzcase.status = diff
      wzcase.save
    end
    redirect_to wz_cases_path, notice: "ok!"
  end

  def confirm
    WzCase.all.each do |cas|
      set_confirm cas
    end
    redirect_to wz_cases_path, notice: "ok!"
  end

  def set_confirm cas
    return unless cas
    return if cas.status == 0
    cas.status = 0
    cas.save
    if cas.wz_query.nil?
      cas.wz_item = nil
      cas.save
      return
    end
    cas.create_wz_item(info: cas.wz_query.info)
  end

  def delete_all
    WzCase.all.each do |v_|
      v_.destroy
    end
    redirect_to wz_cases_path, notice: "ok!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wz_cases_helper.rb
module WzCasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
  <title>违章接口验证</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= yield :head %>
</head>

<body>
<section class="wrapper scrollable">
  <nav class="main-menu">
    <ul>
      <li>
        <a href=<%= wz_cases_path %>>
          <i class="icon-table nav-icon"></i>
          <span class="nav-text">
          主页
          </span>
        </a>
      </li>
      <li>
        <a href=<%= new_wz_case_path %>>
          <i class="icon-table1 nav-icon"></i>
          <span class="nav-text">
          上传车辆
          </span>
        </a>
      </li>
    </ul>
    <%= yield :nav %>
  </nav>
  <%= yield %>
</section>
</body>
</html>

app/views/wz_cases/index.html.erb
<% content_for :nav do %>
    <ul>
      <li class="has-subnav">
        <a href=<%= delete_all_wz_cases_path %> onClick="return confirm('确定?');">
          <i class="icon-angle-right" aria-hidden="true"></i>
          <span class="nav-text">
          删除所有case
          </span>
        </a>
      </li>
      <li class="has-subnav">
        <a href=<%= confirm_wz_cases_path %>>
          <i class="icon-angle-right" aria-hidden="true"></i>
          <span class="nav-text">
          设为基准
          </span>
        </a>
      </li>
      <li class="has-subnav">
        <a href=<%= wz_cases_path + "?type=0" %>>
          <i class="icon-angle-right" aria-hidden="true"></i>
          <span class="nav-text">
          一致
          </span>
        </a>
      </li>
      <li class="has-subnav">
        <a href=<%= wz_cases_path + "?type=1" %>>
          <i class="icon-angle-right" aria-hidden="true"></i>
          <span class="nav-text">
          结果包含基准
          </span>
        </a>
      </li>
      <li class="has-subnav">
        <a href=<%= wz_cases_path + "?type=2" %>>
          <i class="icon-angle-right" aria-hidden="true"></i>
          <span class="nav-text">
          不一致
          </span>
        </a>
      </li>
    </ul>
<% end %>

<a href=<%= begin_wz_cases_path %>>
  <button class="btn btn-default w3ls-button">开始测试</button>
</a>
<%= will_paginate @wz_cases unless @wz_cases.is_a? Array %>
<div style="overflow-x: auto; overflow-y: auto;width:100%;">
  <table>
    <thead>
    <tr>
      <th>id</th>
      <th>城市</th>
      <th>车牌</th>
      <th>车架</th>
      <th>发动机</th>
      <th>标准结果</th>
      <th>当前结果</th>
      <th>结果分析</th>
      <th>删除记录</th>
    </tr>
    </thead>
    <tbody>
    <% @wz_cases.each do |item| %>
        <tr>
          <td><%= link_to item.id, wz_case_path(item) %></td>
          <td><%= item.vehicle.cityname %></td>
          <td><%= link_to item.vehicle.plate, wz_case_path(item) %></td>
          <td><%= item.vehicle.frame %></td>
          <td><%= item.vehicle.engine %></td>
          <td><%= link_to item.get_wz_items.size, wz_case_path(item) %></td>
          <td><%= link_to item.get_wz_queries.size, wz_case_path(item) %></td>
          <td><%= link_to WzCase.get_des(item.status), wz_case_path(item) %></td>
          <td><%= link_to "删除记录", wz_case_path(item), method: :delete %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/wz_cases/new.html.erb
<h1>上传车辆信息</h1>
<%= form_tag(wz_cases_path, method: "post",:multipart=>true) do%>
    <label for = "inputMainData"> 车辆信息数据：</label>
    <input type="file" name="fileMain" id = "inputMainData">
    <!--<p class = "instructions"> xlsx文件</p> -->
    <input type="submit" value ="上传">
<% end %>

app/views/wz_cases/show.html.erb
<div class="progressbar-heading grids-heading">
  <h3><%=@item.id.to_s + " " + @item.vehicle.plate%></h3>
</div>
<%= form_tag(wz_case_path(@item), method: "put", class: "form-inline") do %>
    <% [@item.wz_item,@item.wz_query].each_with_index do |wz,i| %>
        <div class="inline-form widget-shadow">
          <div class="form-title">
            <h4><%= i == 0 ? "基准" : "当前结果" %></h4>
          </div>
          <table>
            <thead>
            <tr>
              <th>序号</th>
              <th>时间</th>
              <th>地点</th>
              <th>详细</th>
            </tr>
            </thead>
            <tbody>
            <% all = wz ? WzCase.parse(wz):[] %>
            <% all.each_with_index do |wz_i,wz_index| %>
                <tr>
                  <td><%= wz_index + 1 %></td>
                  <td><%= wz_i.fetch(:time,"") %></td>
                  <td><%= wz_i.fetch(:address,"") %></td>
                  <td><%= wz_i.fetch(:info,"") %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
    <% end %>
    <button type="submit" class="btn btn-default w3ls-button">设置为基准</button>
<% end %>